services:
  migrate:
    build:
      context: ./webapp
      dockerfile: Dockerfile.prod
    env_file:
      - .env.migrate
    command: flask db upgrade
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./webapp/app/import_data:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile.prod
    env_file:
      - .env.webapp
    environment:
      FLASK_APP: migrate_app.py
      #DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: production
    depends_on:
      db:
        condition: service_healthy
    command: ./entrypoint.sh

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      webapp:
        condition: service_started
    restart: on-failure   
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

# Define a volume to persist our database data
volumes:
  postgres_data:
